export enum AppAction {
  TEST_VALUE = "TEST_VALUE",
  SHOW_SIDEBAR = "SHOW_SIDEBAR",
  CURRENT_USER_DATA = "CURRENT_USER_DATA" ,
  EVALUACIONES = "EVALUACIONES" ,
  EVALUACION = "EVALUACION" ,
  PREGUNTAS_RESPUESTAS="PREGUNTAS_RESPUESTAS",
  SIZE_PREGUNTAS="SIZE_PREGUNTAS",
  PREGUNTAS_RESPUESTAS_ESTUDIANTES="PREGUNTAS_RESPUESTAS_ESTUDIANTES",
  DIRECTORES="DIRECTORES",
  ESTUDIANTES="ESTUDIANTES",
  PREGUNTAS_RESPUESTAS_ESTUDIANTES_INITIAL_VALUE="PREGUNTAS_RESPUESTAS_ESTUDIANTES_INITIAL_VALUE"
}